import {
    FileText,
    Users,
    Upload,
    TrendingUp,
    Settings,
    ShoppingBag,
    Plus,
    LogOut,
    Euro,
    Calendar,
    CheckCircle,
    Calculator,
    MessageSquare,
    Key,
    DollarSign,
    AlertCircle,
    Shield,
    Package,
    Gift,
    Globe,
    Star,
    Zap,
    Store,
    ShieldAlert,
    UserX,
    Terminal,
    Activity,
    Bot,
    Link2,
    Youtube,
    RotateCcw,
    Lock,
    Layout
} from 'lucide-react'

export const DEFAULT_FEATURES = [

    {
        id: 'invoice-designer',
        href: '/dashboard/invoice-designer',
        title: 'Invoice Designer',
        description: 'تصميم قوالب الفواتير والألوان والمواقع',
        icon: Layout,
        iconBg: 'bg-gradient-to-r from-blue-600 to-cyan-500',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-blue-300 bg-gradient-to-br from-white to-blue-50',
        badge: 'NEW',
        badgeClass: 'bg-blue-100 text-blue-700',
        hasPing: true,
        pingColor: 'bg-blue-400',
        pingDotColor: 'bg-blue-500'
    },
    {
        id: 'csv-import',
        href: '/upload',
        title: 'CSV-Import',
        description: 'Shopify-Bestellungen importieren',
        icon: Upload,
        iconBg: 'bg-gradient-to-r from-purple-500 to-purple-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer'
    },
    {
        id: 'digital-products',
        href: '/digital-products',
        title: 'Digitale Produkte',
        description: 'Lizenzschlüssel und Downloads verwalten',
        icon: Package,
        iconBg: 'bg-gradient-to-r from-blue-600 to-indigo-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer',
        iconShadow: 'shadow-md'
    },
    {
        id: 'product-import',
        href: '/products/import',
        title: 'Produkt Import',
        description: 'Produkte von URL importieren (Shopify & mehr)',
        icon: Globe,
        iconBg: 'bg-gradient-to-r from-blue-500 to-cyan-500',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-blue-300 bg-gradient-to-br from-white to-blue-50',
        badge: 'NEU',
        badgeClass: 'bg-blue-100 text-blue-700',
        hasPing: true,
        pingColor: 'bg-blue-400',
        pingDotColor: 'bg-blue-500'
    },
    {
        id: 'shopify',
        href: '/shopify',
        title: 'Shopify Integration',
        description: 'Shop direkt verbinden',
        icon: ShoppingBag,
        iconBg: 'bg-gradient-to-r from-green-500 to-green-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer'
    },
    {
        id: 'kaufland',
        href: '/invoices?search=Kaufland',
        title: 'Kaufland',
        description: 'Kaufland Bestellungen & Rechnungen',
        icon: Store,
        iconBg: 'bg-gradient-to-r from-blue-400 to-cyan-500',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-blue-300 bg-gradient-to-br from-white to-blue-50',
        badge: 'NEW',
        badgeClass: 'bg-blue-100 text-blue-700'
    },
    {
        id: 'buchhaltung',
        href: '/buchhaltung',
        title: 'Buchhaltung',
        description: 'Vollständige Buchführung für Steuerberater',
        icon: Calculator,
        iconBg: 'bg-gradient-to-r from-blue-500 to-blue-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer'
    },
    {
        id: 'purchase-invoices',
        href: '/purchase-invoices',
        title: 'Einkaufsrechnungen',
        description: 'Belege erfassen, verwalten & OCR-Upload',
        icon: FileText,
        iconBg: 'bg-gradient-to-r from-teal-500 to-emerald-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-teal-300 bg-gradient-to-br from-white to-teal-50',
        badge: 'NEU',
        badgeClass: 'bg-teal-100 text-teal-700',
        hasPing: true,
        pingColor: 'bg-teal-400',
        pingDotColor: 'bg-teal-500'
    },
    {
        id: 'reviews',
        href: '/reviews',
        title: 'Produkt Reviews',
        description: 'Bewertungen sammeln & verwalten (Loox Style)',
        icon: Star,
        iconBg: 'bg-gradient-to-r from-yellow-400 to-orange-500',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-yellow-300 bg-gradient-to-br from-white to-yellow-50',
        badge: 'NEU',
        badgeClass: 'bg-yellow-100 text-yellow-700',
        hasPing: true,
        pingColor: 'bg-yellow-400',
        pingDotColor: 'bg-yellow-500'
    },
    {
        id: 'support',
        href: '/support',
        title: 'Support Center',
        description: 'Kundenanfragen und Tickets verwalten',
        icon: MessageSquare,
        iconBg: 'bg-gradient-to-r from-blue-500 to-indigo-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-blue-300 bg-gradient-to-br from-white to-blue-50',
        badge: 'NEU',
        badgeClass: 'bg-blue-100 text-blue-700',
        hasPing: true,
        pingColor: 'bg-red-400',
        pingDotColor: 'bg-red-500'
    },
    {
        id: 'dunning',
        href: '/dunning',
        title: 'Mahnwesen',
        description: 'Automatische Zahlungserinnerungen & Mahnungen',
        icon: AlertCircle,
        iconBg: 'bg-gradient-to-r from-red-500 to-rose-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-red-300 bg-gradient-to-br from-white to-red-50',
        badge: 'AUTO',
        badgeClass: 'bg-red-100 text-red-700'
    },
    {
        id: 'marketing',
        href: '/settings/marketing',
        title: 'Marketing',
        description: 'Automatische Rabatte und Kundenbindung',
        icon: Gift,
        iconBg: 'bg-gradient-to-r from-pink-500 to-rose-500',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-pink-300 bg-gradient-to-br from-white to-pink-50',
        badge: 'AUTO',
        badgeClass: 'bg-pink-100 text-pink-700'
    },
    {
        id: 'abandoned-carts',
        href: '/dashboard/abandoned-carts',
        title: 'Warenkorb Wiederherstellung',
        description: 'Verlorene Warenkörbe retten & Umsatz steigern',
        icon: ShoppingBag,
        iconBg: 'bg-gradient-to-r from-emerald-500 to-teal-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-emerald-300 bg-gradient-to-br from-white to-emerald-50',
        badge: 'NEU',
        badgeClass: 'bg-emerald-100 text-emerald-700',
        hasPing: true,
        pingColor: 'bg-emerald-400',
        pingDotColor: 'bg-emerald-500'
    },
    {
        id: 'api-keys',
        href: '/settings/api-keys',
        title: 'API Zugang',
        description: 'API-Schlüssel für externe Anwendungen verwalten',
        icon: Key,
        iconBg: 'bg-gradient-to-r from-indigo-500 to-purple-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-indigo-300 bg-gradient-to-br from-white to-indigo-50'
    },
    {
        id: 'live-analytics',
        href: '/dashboard/live-analytics',
        title: 'Live Besucher & Session Analytics',
        description: 'Echtzeit-Überwachung des Kundenverhaltens',
        icon: Activity,
        iconBg: 'bg-gradient-to-r from-orange-500 to-red-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-orange-300 bg-gradient-to-br from-white to-orange-50',
        badge: 'LIVE',
        badgeClass: 'bg-orange-100 text-orange-700',
        hasPing: true,
        pingColor: 'bg-orange-400',
        pingDotColor: 'bg-orange-500'
    },
    {
        id: 'extended-analytics',
        href: '/dashboard/analytics',
        title: 'Shop Analytics (Erweitert)',
        description: 'Vollständige Analyse von Traffic, Geräten & Zeit',
        icon: TrendingUp,
        iconBg: 'bg-gradient-to-r from-blue-600 to-blue-700',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-blue-300 bg-gradient-to-br from-white to-blue-50',
        badge: 'NEW',
        badgeClass: 'bg-blue-100 text-blue-700',
        hasPing: true,
        pingColor: 'bg-blue-400',
        pingDotColor: 'bg-blue-500'
    },

    {
        id: 'ai-automation',
        href: '/ai-automation',
        title: 'AI Automation Center',
        description: 'Autonome KI-Inhalte für Shopify (24/7 Betrieb)',
        icon: Bot,
        iconBg: 'bg-gradient-to-r from-violet-600 to-fuchsia-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-violet-300 bg-gradient-to-br from-white to-violet-50',
        badge: 'PRO',
        badgeClass: 'bg-violet-100 text-violet-700',
        hasPing: true,
        pingColor: 'bg-violet-400',
        pingDotColor: 'bg-violet-500'
    },
    {
        id: 'seo-intelligence',
        href: '/seo-intelligence',
        title: 'SEO Intelligence',
        description: 'Autonome SEO-Optimierung & Ranking-Wachstum (24/7 KI)',
        icon: TrendingUp,
        iconBg: 'bg-gradient-to-r from-emerald-600 to-teal-500',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer border-2 border-transparent hover:border-emerald-300 bg-gradient-to-br from-white to-emerald-50',
        badge: 'NEU',
        badgeClass: 'bg-emerald-100 text-emerald-700',
        hasPing: true,
        pingColor: 'bg-emerald-400',
        pingDotColor: 'bg-emerald-500'
    },
    {
        id: 'settings',
        href: '/settings',
        title: 'Einstellungen',
        description: 'Konto und Firma konfigurieren',
        icon: Settings,
        iconBg: 'bg-gradient-to-r from-gray-500 to-gray-600',
        cardClass: 'hover:shadow-lg transition-shadow cursor-pointer'
    }
]
